language: python
dist: xenial
python:
  - "3.6"

branches:
  only:
  - master
  - release

stages:
  - Check
  - Publish

before_install:
  - pip install poetry

install:
  - poetry install

jobs:
  include:
    - stage: Check
      script: poetry run cover
    - stage: Publish
      if: branch = master
      script: skip
      before_deploy:
        - poetry config http-basic.pypi $PYPI_USERNAME $PYPI_PASSWORD
        - poetry build -f sdist
      deploy:
        provider: script
        script: poetry publish
        skip_cleanup: true
