language: python
dist: xenial
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

before_install:
  - pip install poetry

install:
  - poetry install

# Run tests for all python versions
script:
  - poetry run cover

# Publish package only for master branch, after all tests have passed
jobs:
  include:
    - stage: deploy
      python: 3.9
      script: skip
      before_deploy:
        - poetry config http-basic.pypi $PYPI_USERNAME $PYPI_PASSWORD
        - poetry build -f sdist
      deploy:
        provider: script
        script: poetry publish
        on:
          branch: master
        skip_cleanup: true
