language: python
dist: xenial
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

branches:
  only:
  - master
  - release

stages:
  - Check
  - Publish

before_install:
  - pip install poetry

install:
  - poetry install

# Run tests for all python versions
script:
  - poetry run cover

# Publish package only for master branch
before_deploy:
  - poetry config http-basic.pypi $PYPI_USERNAME $PYPI_PASSWORD
  - poetry build -f sdist
deploy:
  provider: script
  script: poetry publish
  skip_cleanup: true
  on:
    branch: master

