language: python
dist: xenial
python:
  - "3.7"

branches:
  only:
  - master
  - release

stages:
  - Check
  - Publish

before_install:
  - pip install poetry

install:
  - poetry install

jobs:
  include:
    - stage: Check
      name: lint
      script: poetry run test
    - stage: Publish
      if: branch = master
      script: skip
      before_deploy:
        - poetry config http-basic.pypi $PYPI_USERNAME $PYPI_PASSWORD
        - poetry build -f sdist
      deploy:
        provider: script
        script: poetry publish
        skip_cleanup: true

after_success:
  poetry run cover
